---
bases:
  - ../../helmfile.d/templates.yaml
  - ../../helmfile.d/environments.yaml

releases:
  - name: tekton-tasks
    chart: ./kustomization
    namespace: tekton-tasks
    createNamespace: true
    labels:
      app: tekton-tasks
