---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-dev
spec:
  generators:
    - git:
        repoURL: https://github.com/OlGe404/gitops-landscape.git
        revision: HEAD
        directories:
          - path: local-dev/*

  template:
    metadata:
      name: "{{ path.basename }}"

    spec:
      project: default
      source:
        repoURL: https://github.com/OlGe404/gitops-landscape.git
        targetRevision: HEAD
        path: "{{ path }}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ path.basename }}"

      syncPolicy:
        automated:
          selfHeal: true
          prune: true

        syncOptions:
          - ApplyOutOfSyncOnly=true
