---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: tekton-pipelines

resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.50.0/release.yaml
