---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
sortOptions:
  order: fifo

commonAnnotations:
  origin: https://github.com/OlGe404/gitops-landscape/local-dev/argocd

commonLabels:
  stage: local-dev

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - nodeport-service.yaml
  - applicationset.yaml
