---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
sortOptions:
  order: fifo

commonAnnotations:
  origin: https://github.com/OlGe404/gitops-landscape/local-dev/argocd

commonLabels:
  gitops-stage: local-dev

resources:
  - base/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.9/manifests/install.yaml
  - base/nodeport-service.yaml
  - base/applicationset.yaml

patches:
  - path: patches/argocd-cm.yaml
  # - path: patches/argocd-initial-admin-secret.yaml
