---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  origin: https://github.com/OlGe404/gitops-landscape/local-dev/tekton-triggers

commonLabels:
  gitops-stage: local-dev
  app.kubernetes.io/instance: tekton-triggers

resources:
  - base/namespace.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.24.1/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.24.1/interceptors.yaml
