---
bases:
  - ../../helmfile.d/templates.yaml
  - ../../helmfile.d/environments.yaml

releases:
  - name: tekton-operator
    chart: ./kustomization
    namespace: tekton-operator
    createNamespace: true
