---
bases:
  - ../../helmfile.d/templates.yaml
  - ../../helmfile.d/environments.yaml

releases:
  - name: tekton-operator
    chart: ./kustomization
    namespace: tekton-operator
    labels:
      app: tekton-operator

  - name: tekton-dashboard
    chart: ./kustomization/tekton-dashboard
    namespace: tekton-pipelines
    labels:
      app: tekton-operator
